version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash
      - sudo yum install -y nodejs
      - node --version
      - npm --version

  build:
    commands:
      - npm install
      - cd client
      - npm install --legacy-peer-deps --loglevel=error
      - VITE_API_URL=http://localhost:3001/ npm run build --force
      - cd ..
      - npm test
