version: 0.2
# Pipeline dedicada para execução de testes

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== CONFIGURANDO AMBIENTE DE TESTES ==="
      - echo "Usando Node.js 20"
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "=== INSTALANDO DEPENDÊNCIAS ==="
      - echo "Instalando dependências do backend (incluindo dev dependencies)"
      - npm install
      - echo "Instalando dependências do frontend"
      - cd client
      - npm install --legacy-peer-deps
      - cd ..

  build:
    commands:
      - echo "=== EXECUTANDO TESTES BACKEND ==="
      - npx jest tests/unit --coverage --watchAll=false
      - echo "=== BUILDANDO FRONTEND ==="
      - cd client
      - VITE_API_URL=http://localhost:3001/ npm run build
      - cd ..
      - echo "=== TESTES CONCLUÍDOS COM SUCESSO ==="

  post_build:
    commands:
      - echo "=== GERANDO RELATÓRIOS ==="
      - echo "Testes executados com sucesso"
      - ls -la coverage/ || echo "Coverage não gerado"
      - ls -la client/dist/ || echo "Build do frontend não encontrado"

reports:
  jest_reports:
    files:
      - junit.xml
    base-directory: .
  coverage_reports:
    files:
      - '**/*'
    base-directory: coverage

artifacts:
  files:
    - coverage/**/*
    - client/dist/**/*
    - junit.xml
  name: TestArtifacts
    