version: 0.2
# Exemplo de buildspec para migração de banco de dados

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências necessárias para migração"
      - npm install -g sequelize-cli

  build:
    commands:
      - echo "realizando npm install"
      - npm install
      - echo "Verificando variáveis de ambiente"
      - echo "DB_HOST=$DB_HOST"
      - echo "DB_NAME=$DB_NAME"
      - echo "NODE_ENV=$NODE_ENV"
      - echo "Executando criação e migração de banco de dados"
      - npx sequelize-cli db:create --debug || echo "Database already exists"
      - npx sequelize-cli db:migrate --debug