version: 0.2
# Exemplo de buildspec para migração de banco de dados

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências necessárias para migração"
      - npm install -g sequelize-cli

  build:
    commands:
      - echo "realizando npm install"
      - npm install
      - echo "Executando criação e migração de banco de dados"
      - npx sequelize-cli db:create || echo "Database already exists"
      - npx sequelize-cli db:migrate