version: 0.2
# Pipeline dedicada para build e push da imagem Docker

phases:
  pre_build:
    commands:
      - echo "=== CONFIGURANDO BUILD DOCKER ==="
      - echo "Fazendo login no ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 397234361193.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=397234361193.dkr.ecr.us-east-1.amazonaws.com/repository-ci/cd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "=== CONSTRUINDO IMAGEM DOCKER ==="
      - echo "Construindo a imagem Docker..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "Imagem construída com sucesso"

  post_build:
    commands:
      - echo "=== ENVIANDO IMAGEM PARA ECR ==="
      - echo "Enviando a imagem Docker para o ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "=== GERANDO ARTEFATOS DE DEPLOY ==="
      - echo "Gerando artefato da imagem para ECS"
      - printf '[{"name":"bia","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Gerando Dockerrun.aws.json para Beanstalk"
      - |
        cat > Dockerrun.aws.json << EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "$REPOSITORY_URI:$IMAGE_TAG",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": 8080,
              "HostPort": 80
            }
          ],
          "Environment": [
            {
              "Name": "NODE_ENV",
              "Value": "production"
            },
            {
              "Name": "DB_HOST",
              "Value": "$DB_HOST"
            },
            {
              "Name": "DB_USER",
              "Value": "$DB_USER"
            },
            {
              "Name": "DB_PWD",
              "Value": "$DB_PWD"
            },
            {
              "Name": "DB_PORT",
              "Value": "$DB_PORT"
            },
            {
              "Name": "DB_NAME",
              "Value": "$DB_NAME"
            }
          ],
          "Logging": "/var/log/nginx"
        }
        EOF
      - echo "=== BUILD DOCKER CONCLUÍDO ==="
      - cat imagedefinitions.json
      - echo "Dockerrun.aws.json criado"

artifacts:
  files:
    - imagedefinitions.json
    - Dockerrun.aws.json
  name: BuildArtifacts