version: 0.2
# Pipeline de testes antes do build

phases:
  install:
    commands:
      - echo "Instalando dependências"
      - curl -fsSL https://deb.nodesource.com/setup_21.x | bash - sudo -
      - sudo yum install -y nodejs

  build:
    commands:
      - echo instalando as dependências da aplicação
      - npm install --loglevel error
      - cd client
      - npm install --legacy-peer-deps --loglevel error
      - VITE_API_URL=http://localhost:3001/ npm run build --force
      - cd ..
      - echo "Iniciando testes"
      - npm test
    