version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Instalando dependências do backend"
      - npm install

  build:
    commands:
      - echo "Buildando frontend com Vite"
      - cd client
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
