version: 0.2
# Pipeline dedicada para execução de testes

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "=== CONFIGURANDO AMBIENTE DE TESTES ==="
      - echo "Usando Node.js 20"
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "=== INSTALANDO DEPENDÊNCIAS ==="
      - echo "Instalando dependências do backend (incluindo dev dependencies)"
      - npm install
      - echo "Reinstalando Jest para garantir instalação correta"
      - npm install jest@27.5.1 --save-dev
      - echo "Recriando symlinks do Jest"
      - rm -f node_modules/.bin/jest
      - ln -sf ../jest/bin/jest.js node_modules/.bin/jest
      - chmod +x node_modules/.bin/jest
      - echo "Verificando instalação do Jest"
      - ls -la node_modules/.bin/ | grep jest || echo "Jest não encontrado"
      - ls -la node_modules/jest/bin/ || echo "Diretório jest/bin não encontrado"
      - echo "Instalando dependências do frontend"
      - cd client
      - npm install --legacy-peer-deps
      - cd ..

  build:
    commands:
      - echo "=== EXECUTANDO TESTES BACKEND ==="
      - npm test
      - echo "=== BUILDANDO FRONTEND ==="
      - cd client
      - VITE_API_URL=http://localhost:3001/ npm run build
      - cd ..
      - echo "=== TESTES CONCLUÍDOS COM SUCESSO ==="

  post_build:
    commands:
      - echo "=== GERANDO RELATÓRIOS ==="
      - echo "Testes executados com sucesso"
      - ls -la coverage/ || echo "Coverage não gerado"
      - ls -la client/dist/ || echo "Build do frontend não encontrado"

reports:
  jest_reports:
    files:
      - junit.xml
    base-directory: .
  coverage_reports:
    files:
      - '**/*'
    base-directory: coverage

artifacts:
  files:
    - coverage/**/*
    - client/dist/**/*
    - junit.xml
  name: TestArtifacts
    